source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'FZWMediaTool_Example' do
  pod 'FZWMediaTool', :path => '../'

  target 'FZWMediaTool_Tests' do
    inherit! :search_paths

    
  end
end
